export const siteConfig = {
  name: "Data Enthusiast of PA Business Solutions",
  legalName: "Data Enthusiast of PA Business Solutions LLC",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.dataenthusiastofpa.com",
  region: "Pennsylvania",
  countryCode: "US",
  serviceAreas: ["Pennsylvania", "United States"],
  phone: "717-802-9344",
  email: "Todd@dataenthusiastofpa.com",
  logoPath: "/icon.png",
  social: {
    linkedin: "https://www.linkedin.com/in/todd-gilmore-86208153",
  },
  defaultTitle: "Procore, Database, and Analytics Engineering",
  defaultDescription:
    "Data Enthusiast of PA builds Procore apps, database systems, and analytics engineering solutions for construction and operations teams in Pennsylvania and across the U.S.",
  keywords: [
    "procore app development",
    "procore workflow automation",
    "procore api development",
    "database engineering services",
    "analytics engineering services",
    "data pipeline development",
    "kpi dashboard development",
    "postgresql consulting",
    "ai upskilling training",
    "ai team training",
    "ai adoption workshop",
    "construction software development",
    "construction operations automation",
    "procore consulting",
    "workflow automation",
    "web app development",
    "mobile app development",
    "procore development",
    "QuickBooks Online integration",
    "API integrations",
    "process automation",
    "custom software development",
  ],
};

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/about", label: "About" },
  { href: "/services", label: "Services" },
  { href: "/services/procore-app-development", label: "Procore" },
  { href: "/services/analytics-engineering", label: "Data & Analytics" },
  { href: "/services/ai-upskilling-training", label: "AI Training" },
  { href: "/industries", label: "Industries" },
  { href: "/contact", label: "Contact" },
];
